# Generated by Django 4.1 on 2022-11-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='videofile',
            field=models.FileField(null='True', upload_to='myimage'),
            preserve_default='True',
        ),
    ]
