# Generated by Django 4.1 on 2022-11-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_image_photo_image_videofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Video',
        ),
    ]
