# Generated by Django 4.1 on 2022-11-28 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_image_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='date',
        ),
    ]
